# Generated by Django 5.2.17 on 2026-09-09 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, default='Bahrain', max_length=100)),
                ('skills', models.TextField(blank=True, help_text='Comma separated skills')),
                ('experience_level', models.CharField(blank=True, choices=[('Student', 'Student'), ('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior'), ('Founder', 'Founder')], max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('industry', models.CharField(choices=[('Technology', 'Technology'), ('AI', 'AI'), ('FinTech', 'FinTech'), ('HealthTech', 'HealthTech'), ('EdTech', 'EdTech'), ('E-Commerce', 'E-Commerce'), ('SaaS', 'SaaS'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Other', 'Other')], default='Technology', max_length=50)),
                ('stage', models.CharField(choices=[('Idea', 'Idea'), ('Building', 'Building'), ('MVP', 'MVP'), ('Launched', 'Launched'), ('Growing', 'Growing')], default='Idea', max_length=20)),
                ('location', models.CharField(default='Bahrain', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='startup_logos/')),
                ('is_recruiting', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StartUpRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('Co-Founder', 'Co-Founder'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Marketing', 'Marketing'), ('Business', 'Business'), ('Sales', 'Sales'), ('Data', 'Data'), ('AI', 'AI'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(blank=True, help_text='Comma separated skills')),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.startuprole')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('applicant', 'role'), name='unique_application_per_role')],
            },
        ),
    ]
