# Generated by Django 5.2.17 on 2026-09-10 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Founder', 'Founder'), ('User', 'User')], default='User', max_length=20),
        ),
        migrations.AddField(
            model_name='startup',
            name='name',
            field=models.CharField(default='Unnamed Startup', max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('startup', 'user'), name='unique_startup_team_member'),
        ),
    ]
